PRODUCTION: Echoes of the Fallen
EPISODE: Pilot - The Hot Gates
DATE: 2026-07-15
PRODUCTION_COMPANY: Scene Reader Studio Technologies LLC

SCENE	001
TITLE	HARBOUR AT DAWN - BODY DISCOVERED
LOCATION	Harbour Docks
INT_EXT	EXT
DAY_NIGHT	DAWN
PAGES	2.0
CAST	MARSH,ROOKIE
JURISDICTION	Georgia
NOTES	Opening crane shot - VFX required

SCENE	002
TITLE	PRECINCT BRIEFING
LOCATION	Police Precinct
INT_EXT	INT
DAY_NIGHT	DAY
PAGES	1.5
CAST	MARSH,ROOKIE,CAPTAIN HOLT,DISPATCH
JURISDICTION	Georgia
NOTES	Exposition - establish world

SCENE	003
TITLE	HARBOUR MASTER INTERVIEW
LOCATION	Harbour Master Office
INT_EXT	EXT
DAY_NIGHT	DAY
PAGES	1.0
CAST	MARSH,HARBOUR MASTER
JURISDICTION	Georgia
NOTES	Key witness interview

SCENE	004
TITLE	BATHROOM INSERT - PHONE RING
LOCATION	Harbour Docks Bathroom
INT_EXT	INT
DAY_NIGHT	NIGHT
PAGES	0.125
CAST	
JURISDICTION	Georgia
NOTES	Insert shot - no cast required

SCENE	005
TITLE	INTERROGATION
LOCATION	Police Precinct Interrogation Room
INT_EXT	INT
DAY_NIGHT	NIGHT
PAGES	2.5
CAST	MARSH,ROOKIE
JURISDICTION	Georgia
NOTES	Key dramatic scene - two-hander

SCENE	006
TITLE	DOCKSIDE BEAT
LOCATION	Harbour Docks
INT_EXT	EXT
DAY_NIGHT	DUSK
PAGES	0.75
CAST	MARSH
JURISDICTION	Georgia
NOTES	Atmospheric transition

SCENE	007
TITLE	NINA ARRIVES AT THE BATTLEFIELD
LOCATION	Ancient Thermopylae - VFX Set
INT_EXT	EXT
DAY_NIGHT	DAY
PAGES	3.0
CAST	NINA ORTIZ,GUIDE
JURISDICTION	California
NOTES	VFX heavy - budget 3x standard day rate

SCENE	008
TITLE	THE FALLEN SPEAK
LOCATION	Ancient Thermopylae - VFX Set
INT_EXT	EXT
DAY_NIGHT	DAWN
PAGES	2.0
CAST	NINA ORTIZ,SPARTAN SOLDIER
JURISDICTION	California
NOTES	Key supernatural sequence

SCENE	009
TITLE	FORENSIC ANALYSIS LAB
LOCATION	University Laboratory
INT_EXT	INT
DAY_NIGHT	DAY
PAGES	1.5
CAST	NINA ORTIZ,DR. CHEN
JURISDICTION	California
NOTES	Science exposition - props required

SCENE	010
TITLE	THE LEAP SEQUENCE
LOCATION	Time Portal Location - Practical + VFX
INT_EXT	EXT
DAY_NIGHT	NIGHT
PAGES	4.0
CAST	NINA ORTIZ
JURISDICTION	New York
NOTES	VFX sequence - may span multiple shoot days
